apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-baseline-settings
resources:
- namespace.yaml
- resource-quota.yaml
- limit-range.yaml
- rbac.yaml
- fim/fim-standin.yaml
- av/av-standin.yaml
- kured/kured.yaml
images:
- name: busybox
  newName: acraksutt6zp2rqfe7w.azurecr.io/live/library/busybox
  newTag: 1.36.1
- name: ghcr.io/kubereboot/kured
  newName: acraksutt6zp2rqfe7w.azurecr.io/live/kubereboot/kured
