apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-ingress-contoso-com-tls-secret-csi-akv
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.key
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.crt
  parameters:
    clientID: 0e8bd87d-d3a9-40ab-b3d7-0192e3984058
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: kv-aks-utt6zp2rqfe7w
    objects: |
      array:
        - |
          objectName: ingress-internal-aks-ingress-contoso-com-tls
          objectType: secret
    tenantID: 42f7676c-f455-423c-82f6-dc2d99791af7
